---
- name: Disable Network Manager 
  hosts: all
  become: true
 
  tasks:
  - name: Change Grub config
    lineinfile:
      path: /etc/default/grub 
      regexp: GRUB_CMDLINE_LINUX
      line: 'GRUB_CMDLINE_LINUX="no_timer_check console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 elevator=noop crashkernel=auto"'

  - name: make grub
    command: "grub2-mkconfig -o /boot/grub2/grub.cfg"



